version: "3.9"
services:
  node:
    container_name: "testedocker"
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/src
    ports:
      - "80:80"
    command: "npm start"
